// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[schoolSlug]/attendance" | "/[schoolSlug]/courses" | "/[schoolSlug]/dashboard" | "/[schoolSlug]/grades" | "/[schoolSlug]/settings" | "/[schoolSlug]/students" | "/[schoolSlug]/subjects" | "/[schoolSlug]/teachers" | "/login" | "/mockups" | "/prototipo-figma" | "/select-school" | "/system" | "/system/dashboard" | "/system/design-system" | "/system/schools" | "/system/schools/new" | "/system/security"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/auth/select-school" | "/api/contact" | "/api/schools/[schoolId]/academic-periods" | "/api/schools/[schoolId]/academic-periods/[periodId]" | "/api/schools/[schoolId]/courses" | "/api/schools/[schoolId]/courses/[courseId]" | "/api/schools/[schoolId]/export" | "/api/schools/[schoolId]/grades" | "/api/schools/[schoolId]/grades/[gradeId]" | "/api/schools/[schoolId]/grades/assessments" | "/api/schools/[schoolId]/grades/assessments/[assessmentId]" | "/api/schools/[schoolId]/grades/bulk" | "/api/schools/[schoolId]/grades/matrix" | "/api/schools/[schoolId]/settings" | "/api/schools/[schoolId]/students" | "/api/schools/[schoolId]/students/[studentId]" | "/api/schools/[schoolId]/subjects" | "/api/schools/[schoolId]/teachers" | "/api/schools/[schoolId]/teachers/[teacherId]" | "/api/schools/[schoolId]/teachers/[teacherId]/assign" | "/api/system/schools" | "/api/system/schools/[schoolId]/status"
type PageRoutes = never
type LayoutRoutes = "/" | "/[schoolSlug]" | "/system"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[schoolSlug]": { "schoolSlug": string; }
  "/[schoolSlug]/attendance": { "schoolSlug": string; }
  "/[schoolSlug]/courses": { "schoolSlug": string; }
  "/[schoolSlug]/dashboard": { "schoolSlug": string; }
  "/[schoolSlug]/grades": { "schoolSlug": string; }
  "/[schoolSlug]/settings": { "schoolSlug": string; }
  "/[schoolSlug]/students": { "schoolSlug": string; }
  "/[schoolSlug]/subjects": { "schoolSlug": string; }
  "/[schoolSlug]/teachers": { "schoolSlug": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/select-school": {}
  "/api/contact": {}
  "/api/schools/[schoolId]/academic-periods": { "schoolId": string; }
  "/api/schools/[schoolId]/academic-periods/[periodId]": { "schoolId": string; "periodId": string; }
  "/api/schools/[schoolId]/courses": { "schoolId": string; }
  "/api/schools/[schoolId]/courses/[courseId]": { "schoolId": string; "courseId": string; }
  "/api/schools/[schoolId]/export": { "schoolId": string; }
  "/api/schools/[schoolId]/grades": { "schoolId": string; }
  "/api/schools/[schoolId]/grades/[gradeId]": { "schoolId": string; "gradeId": string; }
  "/api/schools/[schoolId]/grades/assessments": { "schoolId": string; }
  "/api/schools/[schoolId]/grades/assessments/[assessmentId]": { "schoolId": string; "assessmentId": string; }
  "/api/schools/[schoolId]/grades/bulk": { "schoolId": string; }
  "/api/schools/[schoolId]/grades/matrix": { "schoolId": string; }
  "/api/schools/[schoolId]/settings": { "schoolId": string; }
  "/api/schools/[schoolId]/students": { "schoolId": string; }
  "/api/schools/[schoolId]/students/[studentId]": { "schoolId": string; "studentId": string; }
  "/api/schools/[schoolId]/subjects": { "schoolId": string; }
  "/api/schools/[schoolId]/teachers": { "schoolId": string; }
  "/api/schools/[schoolId]/teachers/[teacherId]": { "schoolId": string; "teacherId": string; }
  "/api/schools/[schoolId]/teachers/[teacherId]/assign": { "schoolId": string; "teacherId": string; }
  "/api/system/schools": {}
  "/api/system/schools/[schoolId]/status": { "schoolId": string; }
  "/login": {}
  "/mockups": {}
  "/prototipo-figma": {}
  "/select-school": {}
  "/system": {}
  "/system/dashboard": {}
  "/system/design-system": {}
  "/system/schools": {}
  "/system/schools/new": {}
  "/system/security": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[schoolSlug]": never
  "/system": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
