// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/select-school/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-school">> = Specific
  const handler = {} as typeof import("../../app/(auth)/select-school/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/attendance">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/courses">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/grades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/grades">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/grades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/settings">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/students">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/subjects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/subjects">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/subjects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[schoolSlug]/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[schoolSlug]/teachers">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mockups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mockups">> = Specific
  const handler = {} as typeof import("../../app/mockups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prototipo-figma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prototipo-figma">> = Specific
  const handler = {} as typeof import("../../app/prototipo-figma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/dashboard">> = Specific
  const handler = {} as typeof import("../../app/system/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/design-system">> = Specific
  const handler = {} as typeof import("../../app/system/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system">> = Specific
  const handler = {} as typeof import("../../app/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/schools/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/schools/new">> = Specific
  const handler = {} as typeof import("../../app/system/schools/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/schools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/schools">> = Specific
  const handler = {} as typeof import("../../app/system/schools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system/security">> = Specific
  const handler = {} as typeof import("../../app/system/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/select-school/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/select-school">> = Specific
  const handler = {} as typeof import("../../app/api/auth/select-school/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/academic-periods/[periodId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/academic-periods/[periodId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/academic-periods/[periodId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/academic-periods/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/academic-periods">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/academic-periods/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/courses/[courseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/courses/[courseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/courses">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/export">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/[gradeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades/[gradeId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/[gradeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/assessments/[assessmentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades/assessments/[assessmentId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/assessments/[assessmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades/assessments">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/matrix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades/matrix">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/matrix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/grades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/grades">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/grades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/settings">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/students/[studentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/students/[studentId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/students/[studentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/students">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/subjects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/subjects">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/subjects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/teachers/[teacherId]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/teachers/[teacherId]/assign">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/teachers/[teacherId]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/teachers/[teacherId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/teachers/[teacherId]">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/teachers/[teacherId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schools/[schoolId]/teachers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schools/[schoolId]/teachers">> = Specific
  const handler = {} as typeof import("../../app/api/schools/[schoolId]/teachers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/schools/[schoolId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/schools/[schoolId]/status">> = Specific
  const handler = {} as typeof import("../../app/api/system/schools/[schoolId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/system/schools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/schools">> = Specific
  const handler = {} as typeof import("../../app/api/system/schools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/[schoolSlug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[schoolSlug]">> = Specific
  const handler = {} as typeof import("../../app/[schoolSlug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/system/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/system">> = Specific
  const handler = {} as typeof import("../../app/system/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
